# Generated by Django 6.0.5 on 2026-06-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de aprobación'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20),
        ),
    ]
