# Generated by Codex on 2026-07-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reservation_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='recurrence_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('SEMANAL', 'Semanal'),
                    ('MENSUAL', 'Mensual'),
                    ('TRIMESTRAL', 'Trimestral'),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
