# Generated by Django 6.0.5 on 2026-06-10 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropuestaPleno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RECHAZADA', 'Rechazada'), ('PRESENTADA', 'Presentada por Registro'), ('FINALIZADA', 'Finalizada')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('numero_registro', models.CharField(blank=True, max_length=100, null=True)),
                ('respuesta_admin', models.TextField(blank=True, null=True)),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
