# Generated by Django 6.0.5 on 2026-06-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plenos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuestapleno',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RECHAZADA', 'Rechazada'), ('PRESENTADA', 'Presentada por Registro'), ('FINALIZADA', 'Finalizada')], default='PENDIENTE', max_length=20),
        ),
    ]
