# Generated by Django 6.0.5 on 2026-06-13 13:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("autor", models.CharField(blank=True, max_length=255)),
                ("editorial", models.CharField(blank=True, max_length=255)),
                ("categoria", models.CharField(blank=True, max_length=255)),
                ("isbn", models.CharField(blank=True, max_length=120, null=True)),
                ("etiqueta", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "disponibilidad",
                    models.CharField(
                        choices=[
                            ("DISPONIBLE", "Disponible"),
                            ("NO_DISPONIBLE", "No disponible"),
                        ],
                        default="DISPONIBLE",
                        max_length=20,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["titulo", "autor"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("isbn__isnull", False),
                            models.Q(("isbn", ""), _negated=True),
                        ),
                        fields=("isbn",),
                        name="libro_isbn_unico_si_existe",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("isbn__isnull", True), ("isbn", ""), _connector="OR"
                        ),
                        fields=("titulo", "autor"),
                        name="libro_titulo_autor_unico_sin_isbn",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PrestamoLibro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_solicitud",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("APROBADA", "Aprobada"),
                            ("RECHAZADA", "Rechazada"),
                            ("PRESTADA", "Prestada"),
                            ("DEVUELTA", "Devuelta"),
                            ("CANCELADA", "Cancelada"),
                            ("VENCIDA", "Vencida"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("fecha_aprobacion", models.DateTimeField(blank=True, null=True)),
                ("fecha_rechazo", models.DateTimeField(blank=True, null=True)),
                ("motivo_rechazo", models.TextField(blank=True, null=True)),
                ("fecha_entrega", models.DateTimeField(blank=True, null=True)),
                ("fecha_prevista_devolucion", models.DateField(blank=True, null=True)),
                ("fecha_devolucion", models.DateTimeField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "administradora",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prestamos_libros_gestionados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "libro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prestamos",
                        to="biblioteca.libro",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestamos_libros",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_solicitud"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("estado__in", ["APROBADA", "PRESTADA", "VENCIDA"])
                        ),
                        fields=("libro",),
                        name="prestamo_libro_unico_activo",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            (
                                "estado__in",
                                ["PENDIENTE", "APROBADA", "PRESTADA", "VENCIDA"],
                            )
                        ),
                        fields=("usuario", "libro"),
                        name="prestamo_libro_unico_usuario_activo",
                    ),
                ],
            },
        ),
    ]
