# Generated by Django 6.0.5 on 2026-06-04 15:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_dni_nif_usuario_es_socio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='autoriza_imagenes',
            field=models.BooleanField(default=False, verbose_name='Autoriza publicación de imágenes'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigo_postal',
            field=models.CharField(blank=True, default='28760', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='domicilio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email_secundario',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email 2'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='entidad_bancaria',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_alta',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Alta'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Baja'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_pago_recibo',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago del Recibo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_alta',
            field=models.BooleanField(default=True, verbose_name='¿Está de Alta?'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='letra',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='localidad',
            field=models.CharField(blank=True, default='Tres Cantos', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nif_titular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_casa',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='piso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='recibo_anual_pagado',
            field=models.BooleanField(default=False, verbose_name='Recibo Anual Pagado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono_movil_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Móvil 2'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='titular_cuenta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='es_socio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero_socio',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
