# Generated by Django 6.0.5 on 2026-06-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_autoriza_imagenes_usuario_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='estado_socio',
            field=models.CharField(choices=[('NO_SOCIO', 'No Socio'), ('PENDIENTE', 'Solicitud Pendiente'), ('ACEPTADA', 'Socio Activo'), ('RECHAZADA', 'Solicitud Rechazada'), ('BAJA_SOLICITADA', 'Baja Solicitada')], default='NO_SOCIO', max_length=20),
        ),
    ]
